spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/payhere?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://mysql-db-container:3306/payhere?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8

---
spring:
  config:
    activate:
      on-profile: test

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
